# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('gym_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=100)),
                ('climb_type', models.CharField(max_length=100)),
                ('climb_picture', models.CharField(max_length=500)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeguide.Gym')),
            ],
        ),
    ]
